services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_tracker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - task-network

  auth-service:
    build:
      context: .
      dockerfile: auth_service/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-secure-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MASTER_USERNAME=admin
      - MASTER_PASSWORD=secret
    depends_on:
      - postgres
    networks:
      - task-network

  task-service:
    build:
      context: .
      dockerfile: task_service/docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - auth-service
      - postgres
    networks:
      - task-network

networks:
  task-network:
    driver: bridge